name: PlantWatch
version: 1.0
main: com.mishanstvo.plantwatch.PlantWatchPlugin
api-version: 1.21
description: A plugin to keep chunks with growing blocks loaded and updated.
commands:
  plantwatch:
    description: Admin commands for PlantWatch plugin
    usage: /plantwatch <subcommand>
    permission: plantwatch.use
    aliases: [cl]
    subcommands:
      reloadconfig:
        description: Reload the configuration file.
        usage: /plantwatch reloadconfig
        permission: plantwatch.reloadconfig
      pause:
        description: Pause chunk updates.
        usage: /plantwatch pause
        permission: plantwatch.pause
      resume:
        description: Resume chunk updates.
        usage: /plantwatch resume
        permission: plantwatch.resume
      stats:
        description: Get statistics about chunk updates.
        usage: /plantwatch stats
        permission: plantwatch.stats
permissions:
  plantwatch.admin:
    description: Allows access to PlantWatch admin commands
    default: op  # Команды доступны только операторам